export const ACTION = {
  GLOBAL: {
    PENDING: {
      UPDATE_CURRENT_PENDING_STATE: 'UPDATE_CURRENT_PENDING_STATE',
    },
    THEME: {
      UPDATE_THEME_STATE: 'UPDATE_THEME_STATE',
      CHANGE_THEME_SUCCESS: 'GET_SYSTEM_THEME_SUCCESS',
      CHANGE_THEME_FAIL: 'GET_SYSTEM_THEME_FAIL',
    },
    SUCCESS: {
      UPDATE_SUCCESS_STATE: 'UPDATE_SUCCESS_STATE',
    },
    FAILURE: {
      UDPATE_FAILURE_STATE: 'UPDATE_FAILIRE_STATE',
    },
  },
  AUTH_ACTION: {},
  PUBLIC_ACTION: {},
};
